# Form implementation generated from reading ui file '.\\templates\\dlgAbout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAbout(object):
    def setupUi(self, dlgAbout):
        dlgAbout.setObjectName("dlgAbout")
        dlgAbout.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        dlgAbout.resize(400, 300)
        dlgAbout.setModal(True)
        self.label = QtWidgets.QLabel(parent=dlgAbout)
        self.label.setGeometry(QtCore.QRect(80, 180, 71, 21))
        self.label.setOpenExternalLinks(True)
        self.label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextBrowserInteraction)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=dlgAbout)
        self.label_2.setGeometry(QtCore.QRect(80, 220, 111, 21))
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextBrowserInteraction)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=dlgAbout)
        self.label_3.setGeometry(QtCore.QRect(80, 140, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setOpenExternalLinks(True)
        self.label_3.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextBrowserInteraction)
        self.label_3.setObjectName("label_3")
        self.btnCerrarAbout = QtWidgets.QPushButton(parent=dlgAbout)
        self.btnCerrarAbout.setGeometry(QtCore.QRect(270, 240, 75, 23))
        self.btnCerrarAbout.setObjectName("btnCerrarAbout")
        self.label_4 = QtWidgets.QLabel(parent=dlgAbout)
        self.label_4.setGeometry(QtCore.QRect(120, 20, 111, 81))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(".\\\\templates\\../img/logo.ico"))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(dlgAbout)
        QtCore.QMetaObject.connectSlotsByName(dlgAbout)

    def retranslateUi(self, dlgAbout):
        _translate = QtCore.QCoreApplication.translate
        dlgAbout.setWindowTitle(_translate("dlgAbout", "Acerca de..."))
        self.label.setText(_translate("dlgAbout", "<a href=\"http://www.iesteis.es\">IES de Teis</a>"))
        self.label_2.setText(_translate("dlgAbout", "Copyright 2024 "))
        self.label_3.setText(_translate("dlgAbout", "Autor: Laura María Rodríguez Rodríguez"))
        self.btnCerrarAbout.setText(_translate("dlgAbout", "Cerrar"))
