# Form implementation generated from reading ui file '.\\templates\\dlgGestionprop.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_Tipoprop(object):
    def setupUi(self, dlg_Tipoprop):
        dlg_Tipoprop.setObjectName("dlg_Tipoprop")
        dlg_Tipoprop.resize(400, 300)
        dlg_Tipoprop.setMinimumSize(QtCore.QSize(400, 300))
        dlg_Tipoprop.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\\\templates\\../img/logo.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlg_Tipoprop.setWindowIcon(icon)
        dlg_Tipoprop.setModal(True)
        self.frame = QtWidgets.QFrame(parent=dlg_Tipoprop)
        self.frame.setGeometry(QtCore.QRect(11, 31, 371, 151))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(parent=self.frame)
        self.widget.setGeometry(QtCore.QRect(60, 30, 251, 114))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(60, 60))
        self.label_2.setMaximumSize(QtCore.QSize(60, 60))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\\\\templates\\../img/logo.ico"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setMinimumSize(QtCore.QSize(200, 20))
        self.label.setMaximumSize(QtCore.QSize(200, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.txtGestipoprop = QtWidgets.QLineEdit(parent=self.widget)
        self.txtGestipoprop.setMinimumSize(QtCore.QSize(180, 20))
        self.txtGestipoprop.setMaximumSize(QtCore.QSize(150, 20))
        self.txtGestipoprop.setObjectName("txtGestipoprop")
        self.gridLayout.addWidget(self.txtGestipoprop, 2, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.layoutWidget = QtWidgets.QWidget(parent=dlg_Tipoprop)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 200, 260, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnAltatipoprop = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnAltatipoprop.setMinimumSize(QtCore.QSize(80, 25))
        self.btnAltatipoprop.setMaximumSize(QtCore.QSize(80, 25))
        self.btnAltatipoprop.setObjectName("btnAltatipoprop")
        self.horizontalLayout.addWidget(self.btnAltatipoprop)
        self.btnDeltipoprop = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btnDeltipoprop.setMinimumSize(QtCore.QSize(80, 25))
        self.btnDeltipoprop.setMaximumSize(QtCore.QSize(80, 25))
        self.btnDeltipoprop.setObjectName("btnDeltipoprop")
        self.horizontalLayout.addWidget(self.btnDeltipoprop)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)

        self.retranslateUi(dlg_Tipoprop)
        QtCore.QMetaObject.connectSlotsByName(dlg_Tipoprop)

    def retranslateUi(self, dlg_Tipoprop):
        _translate = QtCore.QCoreApplication.translate
        dlg_Tipoprop.setWindowTitle(_translate("dlg_Tipoprop", "Gestión Tipo Propiedades"))
        self.label.setText(_translate("dlg_Tipoprop", "Gesión tipo de propiedad"))
        self.btnAltatipoprop.setText(_translate("dlg_Tipoprop", "Alta"))
        self.btnDeltipoprop.setText(_translate("dlg_Tipoprop", "Eliminar"))
